services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: assetflow
      POSTGRES_PASSWORD: assetflow
      POSTGRES_DB: asset_flow
    ports:
      - '5432:5432'
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

volumes:
  pgdata_dev:
